### ISSUE TITLE
Hologram disappeares after /reload

### ISSUE THREAD

**Issue by Pankraz01** [sainttx/Holograms#100]
hey folks,

Holograms disappear after typing `/rl confirm`, so you need to run `/h reload` to bring them back 
Is there a way to fix this?

I am using the _latest_ version of paperMC and Holograms

**Comment by microwin7** [comment]
I also disappear, 1.8.8 version, rebooted the server and there are no block animations until I do / holo reload

**Comment by microwin7** [comment]
Somehow connected to this plugin MultiVerseCore. If you turn it off, there will be no such problem. But I could not find the error, there is a very similar server, the whole configuration is the same in these plugins. Perhaps something in the kernel settings allows the MultiVerseCore plugin to do this.

**Comment by Pankraz01** [comment]
> Somehow connected to this plugin MultiVerseCore. If you turn it off, there will be no such problem. But I could not find the error, there is a very similar server, the whole configuration is the same in these plugins. Perhaps something in the kernel settings allows the MultiVerseCore plugin to do this.

Have you checked the MVC Code on GitHub too, or just this plugin?

**Comment by microwin7** [comment]
checked disconnecting plugins separately

**Comment by ahhahaah** [comment]
ye me too having same issue but i cant turn off multiverse core :(

**Comment by ahhahaah** [comment]
someone help!!

**Comment by Pankraz01** [comment]
Try switching to HolographicDisplays. Its the same plugin, but the devs are active. It seems the dev is not taking care about his plugin anymore...
