### ISSUE TITLE
Error and plugin won't start

### ISSUE THREAD

**Issue by dkim19375** [sainttx/Holograms#110]
I'm getting an error that won't let Holograms start, how do I fix it?
`[Holograms] The plugin couldn't create the NMS controller instance and has been disabled. This is likelydue to no supported Hologram implementation for your CraftBukkit/Spigot version.`

**Comment by lwatsondev** [comment]
1.16.2 isn't supported yet.

**Comment by wyatt-herkamp** [comment]
Pull Request is open with the update. https://github.com/sainttx/Holograms/pull/111
You can download it. https://github.com/wherkamp/Holograms/releases/tag/2.13.1

**Comment by JuiceWaAaH2021** [comment]
![image](https://user-images.githubusercontent.com/88655876/145750109-c013ae41-5c28-44f2-a0f3-e7948d134307.png)

**Comment by JuiceWaAaH2021** [comment]
> ![image](https://user-images.githubusercontent.com/88655876/145750109-c013ae41-5c28-44f2-a0f3-e7948d134307.png)

help, how to fix this

**Comment by dkim19375** [comment]
> > ![image](https://user-images.githubusercontent.com/88655876/145750109-c013ae41-5c28-44f2-a0f3-e7948d134307.png)
> 
> help, how to fix this

uhh please make a new issue with console logs
