### ISSUE TITLE
Floating items dont work! ASAP

### ISSUE THREAD

**Issue by Fanz2003** [sainttx/Holograms#12]
So when i do /hd addline (name) item:399 it add a line that says item:399! Please help!!!

**Comment by stapleshotz** [comment]
So I'm not sure if you know, but this is the issues page for the plugin called Holograms by SainttX.
"/hd" is (I'm guessing) a command from the plugin called Holographic Displays by filoghost. http://dev.bukkit.org/bukkit-plugins/holographic-displays/
It's not a command for this plugin that I know of.
