### ISSUE TITLE
Error at line 28 :/

### ISSUE THREAD

**Issue by ghost** [sainttx/Holograms#14]
`com.sainttx.holograms.util.LocationUtil.stringAsLocation(LocationUtil.java:28)`

i just restarted my server and this came up in console, here is the whole error below:

`09.06 12:45:09 [Server] WARN [Holograms] Task #38814 for Holograms v2.2.0-SNAPSHOT generated an exception
09.06 12:45:09 [Server] INFO java.lang.NullPointerException
09.06 12:45:09 [Server] INFO at com.sainttx.holograms.util.LocationUtil.stringAsLocation(LocationUtil.java:28) ~[?:?]
09.06 12:45:09 [Server] INFO at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:42) ~[?:?]
09.06 12:45:09 [Server] INFO at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:49) ~[?:?]
09.06 12:45:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
09.06 12:45:09 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

**Comment by AFKGames** [comment]
help?

**Comment by zreed** [comment]
One of your holograms doesn't have a location.
