### ISSUE TITLE
Could not load 'plugins/Holograms-2.3.0-SNAPSHOT.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by GameBoy1510** [sainttx/Holograms#21]
Hey there, need a bit of help. Trying to install Holograms on my 1.10.2 Spigot MC Server. However when i install snapshot 2.3.0 (which is supposed to be compatible with 1.10?) I Receive the error:

Could not load 'plugins/Holograms-2.3.0-SNAPSHOT.jar' in folder 'plugins'.

In my experience this error with plugins normally means there's some problem with version compatibility but as far as I can tell it should work fine.
If you want the full error log I can post it to you but its simply strings of java errors. Thanks for your time any fix you could suggest would be appreciated know i'm not giving you much to work with. :smile:

**Comment by sainttx** [comment]
Please post the full error log
