### ISSUE TITLE
/holograms refresh not exist! Impossible refresh/reload configuration!

### ISSUE THREAD

**Issue by MaGoFaRcO** [sainttx/Holograms#22]
With this plugin (or at least this version) is not possible in any way to reload the configuration, then you can not manipulate the hologram from the files (very comfortable thing I always do with HD), does not work from the console, and even from in-game owner with permissions, the command seems not to exist and does not appear either in the /holograms help! please update adding this fundamental option! Thank you.

Versions details:
Server version: Spigot 1.8.8
Plugin Version, Holograms v2.3.0-SNAPSHOT

**Comment by sainttx** [comment]
This was added in 7954682a0a9302bda2080e11c44549eeb1470662
