### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by EdwardtheWard** [sainttx/Holograms#25]
Hello, I've been trying to setup placeholders for player usernames. I've installed the 3 required plugins, Holograms, HologramsPlaceHolders, and PlaceHolderAPI. As I typed in the line "Welcome, %player_name%!", %player_name% didn't return as a playername, but as a text '%player_name%'. 

Server Version: Spigot 1.8.8
Plugin(s) version: All compatible for spigot 1.8.8

**Comment by sainttx** [comment]
Are there any errors in the console? Have you enabled the placeholders in PlaceholderAPI config? I haven't tested with the latest version of PAPI but it should function as intended.
