### ISSUE TITLE
Hologram keeps resetting to previous state/not saving

### ISSUE THREAD

**Issue by MTM123** [sainttx/Holograms#28]
Hologram keeps resetting to previous state after restarting(not /reload). There are no errors related to Holograms neither when starting or stopping the server. I have also tried execute /save-all(not sure if it does something related with entities though) and waiting few minutes. 

Plugins and version:
http://i.imgur.com/2tsf6we.png

**Comment by sainttx** [comment]
Holograms version and method/commands used to re-create the issue?

**Comment by MTM123** [comment]
Holograms v2.4.0
/holo create
/holo insertline
/holo setline
