### ISSUE TITLE
1.12 Update

### ISSUE THREAD

**Issue by Behoston** [sainttx/Holograms#31]
After 1.12 update holograms doesn't work

**Comment by outspier** [comment]
I've taken the liberty of half-assedly updating it to 1.12 myself until saint updates it properly. View my fork if you want a (working?) 1.12 to compile.

**Comment by BrannonBlair** [comment]
Tried compiling, said I was missing a metrics dependency. Not sure what else to do :/.=

**Comment by Behoston** [comment]
Try to remove metrics dependency... it's required only for statistics
