### ISSUE TITLE
The Repo is down 

### ISSUE THREAD

**Issue by Rocologo** [sainttx/Holograms#34]
our repository seems to be down.

<repositories>
  <repository>
    <id>maven.sainttx.com</id>
    <url>http://maven.sainttx.com/nexus/content/groups/public/</url>
  </repository>
</repositories>

I get error 404 when I try to browse the repo?

**Comment by mihai-safta-hs** [comment]
Ditto

**Comment by Mishyy** [comment]
Still down @sainttx
