### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ReaperofSouls89** [sainttx/Holograms#46]
So I've downloaded all the necessary plugins for my server but I still cant seem to get this to work.  When ever I try to create a hologram I get this isnstead, internal server error.  I check the console and it just null.  Any tutorials or how to's on downloading and setting up the plugin?  When I open up the plugin folder there isnt a config just holograms.yml.  Should there be a config and is this usable with minecraft v1.14.2?

**Comment by sainttx** [comment]
Please post the error

**Comment by ReaperofSouls89** [comment]
Sorry I figured it out, anyway to make the texts bigger?

**Comment by ReaperofSouls89** [comment]
Nvm I started getting this

Server thread/ERROR Could not pass event ChunkLoadEvent to Holograms v2.8-SNAPSHOT

**Comment by sainttx** [comment]
Discussion moved to #71, try upgrading to Holograms version 2.9 or above and reporting whether the problem persists

**Comment by ReaperofSouls89** [comment]
I got it working ty


Sent from Yahoo Mail for iPhone


On Saturday, August 3, 2019, 9:07 AM, Matthew Steglinski <notifications@github.com> wrote:


Discussion moved to #71, try upgrading to Holograms version 2.9 or above and reporting whether the problem persists
