### ISSUE TITLE
bug 1.14.2 paper

### ISSUE THREAD

**Issue by slvlr** [sainttx/Holograms#47]
https://pastebin.com/nC8ZJvPs

**Comment by slvlr** [comment]
and this  is this an issue with crates or holograms? https://pastebin.com/VsmTkbr6

**Comment by MamiyaOtaru** [comment]
bukkitEntity is private now.  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fa71719350d15fd5d5091c4fe45ff2e86a95371c

**Comment by sainttx** [comment]
Duplicate of #45
