### ISSUE TITLE
Holograms not working in 1.14.2

### ISSUE THREAD

**Issue by Wynandus** [sainttx/Holograms#52]
The plugin works but once you create a hologram you are not able to see them.
Please fix this (btw. if i remove protocolsupport they work but i need it on my server)

**Comment by JoelDesante** [comment]
I have the same issue. I too am using ProtocolSupport. There are no errors in the console, everything says that it is loaded. They work when I log into the server with a client below 1.14.x but not when I log in with 1.14.x

**Comment by JoelDesante** [comment]
This issue seems to have been resolved in the latest update of ProtocolSupport.
