### ISSUE TITLE
Crashes my 1.14.2 server

### ISSUE THREAD

**Issue by STR1KEStudioz** [sainttx/Holograms#54]
Plugin crashes my server until disabled

**Comment by Dreandor** [comment]
I can agree with that. It generate a Loop and let the server crash.

**Comment by iTheCuteKitten** [comment]
I have the exact same problem. My server works for about 1 - 3 minutes and then crashes randomly.

**Comment by sainttx** [comment]
Discussion moved to #71, try upgrading to Holograms version 2.9 or above and reporting whether the problem persists
