### ISSUE TITLE
Not working after reload/restart

### ISSUE THREAD

**Issue by bobbyjo31** [sainttx/Holograms#55]
I make a hologram and when i restart or reload with plugman they disappear please help me!
WARN [Holograms] Failed to spawn Hologram "Devil"
28.06 20:21:15 [Server] INFO com.sainttx.holograms.api.exception.HologramEntitySpawnException: Attempted to spawn hologram entity in invalid chunk
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:74) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:40) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:47) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:130) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:119) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:58) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:39) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
28.06 20:21:15 [Server] INFO Caused by: java.lang.NullPointerException
28.06 20:21:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.getHandle(CraftChunk.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.<init>(CraftChunk.java:30) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
28.06 20:21:15 [Server] INFO at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:72) ~[Holograms-2.8%20(1).jar:?]
28.06 20:21:15 [Server] INFO ... 13 more

**Comment by sainttx** [comment]
1.8 is legacy and no longer supported, a future version may fix this however switching to HolographicDisplays would be a better just for now
