### ISSUE TITLE
TPS decreasing 

### ISSUE THREAD

**Issue by Achent007** [sainttx/Holograms#58]
Hello, 

When i use your plugin on my server (1.14.3 paper-127 and holograms V2.8), i have a big problem. When i reach 5 players on my tps start to drop. 
I know the tps drop is due to Minecraft 1.14 but i have 50% of overloading due to Holograms. Can you fix the usage of the server ressource please

Look my timings report https://timings.aikar.co/?id=52c23fb8ed0e4c1db26099776587b871

**Comment by sainttx** [comment]
Try updating to version 2.9 or above, reopen the issue if the problem persists
