### ISSUE TITLE
Unable to change item line

### ISSUE THREAD

**Issue by Iwitrag** [sainttx/Holograms#65]
I'm trying to change item line, but it says 

> Line 2 of a hologram is not a text line and cannot be modified.

I have issued this command:

`/hd setline spawngo4 2 item:stick 1`

trying to change from 'item:wooden_hoe' to stick.

On Spigot page there is info that it's possible to use /hd setline to change item hologram, but it doesn't work.

Using version 2.8-SNAPSHOT

**Comment by natr566** [comment]
Your best bet would be heading over to the config file and changing it there then reloading the plugin.

**Comment by Iwitrag** [comment]
> Your best bet would be heading over to the config file and changing it there then reloading the plugin.

No way, reloading is not recommended.
It should be normally able to change item line, it's a bug.

**Comment by natr566** [comment]
Reload the plugin, not you're whole server.

**Comment by Iwitrag** [comment]
> Reload the plugin, not you're whole server.

So to change 1 hologram line I need to reload entire plugin? Seriously?
I have much better workaround: just remove the line and insert it again... 

BUT if its advertised as example on intro page on Spigot then it should definitely work to be able to change it directly with 1 command.

**Comment by sainttx** [comment]
Line indexes start at 0, so what you may consider the second line is at index 1. Try the setline command with 1 instead of 2.

**Comment by Iwitrag** [comment]
I have this hologram:

Line 0: Please do NOT build around spawn
Line 1: You can use wooden hoe to create protection
Line 2: item:wooden_hoe
Line3: Enjoy your game :)

**Comment by sainttx** [comment]
Do you have HolographicDisplays loaded as well? `/hd` is not a registered command alias with Holograms so you may be trying to use the wrong plugin, try one of the following:
* /holograms
* /hologram
* /holo
* /h

**Comment by Iwitrag** [comment]
No I don't. I'm using betterAlias. But I have tried it also with holograms and same result.

**Comment by sainttx** [comment]
I see what the issue is, will fix in a future update.

For now I would recommend using the insertline subcommand and then deleting the existing line.
