### ISSUE TITLE
show player in 3worlds to e.g bedwarslobby and bedwars game

### ISSUE THREAD

**Issue by damiencoop2** [sainttx/Holograms#66]
how do i {world: skyblock} and how do i more wolrds e.g {world: skyblock,askyblock,askyblock_nether}

**Comment by natr566** [comment]
Grab the 
Placeholder addon - https://www.spigotmc.org/resources/holograms-placeholders.19813/
It does also require 
ProtocolLib - https://www.spigotmc.org/resources/protocollib.1997/
PlaceholderAPI - https://www.spigotmc.org/resources/placeholderapi.6245/
**Players**
After you have all these installed on your server do /papi ecloud download Bungee
Then you can use the placeholder {listplayers_in_world_<worldname>}

**More Placeholders**
If you do all the above and it still dosent give you exacly what your are looking for head over to - https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server
