### ISSUE TITLE
Holograms causing server crash

### ISSUE THREAD

**Issue by Sorry** [sainttx/Holograms#69]
Seems to crash upon teleporting to a player - This was also my crash report: https://pastebin.com/18vjCxmx

[2019-07-31-13.log.gz](https://github.com/sainttx/Holograms/files/3454548/2019-07-31-13.log.gz)

**Comment by iTheCuteKitten** [comment]
I have the exact same problem. My server works for about 1 - 3 minutes and then crashes randomly.

**Comment by sainttx** [comment]
Discussion moved to #71, try upgrading to Holograms version 2.9 or above and reporting whether the problem persists
