### ISSUE TITLE
Hey my server keeps crashing cause of holograms HELP pls

### ISSUE THREAD

**Issue by aloranetwork** [sainttx/Holograms#70]
https://pastebin.com/HJH5JT0A

heres my plugin list
Anticooldown.jar
chatcontrol
citizens
crateplus
dailyrewards
Essentials
FActions
Holograms
Horizon
Jobs
KixCHatannouncer
LuckPerms
massivecore
Mineablespawners
nuvotifier
votingplugin
ProtocolLIB
Rankgrantplus
serverlistplus
tab v2.4.15
vault
wildtp
worldedit
worldguard

**Comment by iTheCuteKitten** [comment]
I have the exact same problem. My server works for about 1 - 3 minutes and then crashes randomly.

**Comment by sainttx** [comment]
Discussion moved to #71, try upgrading to Holograms version 2.9 or above and reporting whether the problem persists
