### ISSUE TITLE
Holograms disappear after restart

### ISSUE THREAD

**Issue by DeltaFalken** [sainttx/Holograms#73]
After I create holograms with the chat commands and restart the server then, they just don't spawn. But I am not getting any error shown in the consol, can you help me fix this problem pls?
My Server is running Spigot 1.12.2 non-bungeecord

**Comment by hwgilbert16** [comment]
I'm having this issue as well, I'm running 1.14.4 though.

Have you figured out how to fix it?

**Comment by DeltaFalken** [comment]
Not yet 😕

**Comment by sainttx** [comment]
Fixed in 07f89c3cfde7ca2e6e83c903660909b1c8f7b03c
