### ISSUE TITLE
Hologram disappears out of nowhere

### ISSUE THREAD

**Issue by brnxx** [sainttx/Holograms#74]
Out of nowhere the hologram disappears and then comes back. I do not know what is.

![image](https://user-images.githubusercontent.com/49076883/62802128-9309f780-babd-11e9-966a-55498d58cd61.png)
![image](https://user-images.githubusercontent.com/49076883/62802135-98674200-babd-11e9-8ba6-4b2e6d5af542.png)

**Comment by sainttx** [comment]
Fixed in 07f89c3cfde7ca2e6e83c903660909b1c8f7b03c
