### ISSUE TITLE
Holograms reverting after server restart and sometimes at random times

### ISSUE THREAD

**Issue by Jaaaaaaaaaaaaaaaaaack** [sainttx/Holograms#8]
The holograms keep reverting back after the server restarts or sometimes they just randomly revert back when the server is up normally. So if I put '&f&lHello' on a hologram, then change it to '&c&lHelllllo', if I then restarted the server, it would revert back to '&f&lHello'. I really hope you could fix this! Absolutely LOVE your plugin! Compatible with ViaVersion....has awesome features...its lightweight....its smooth....its easy to use! Keep up the good work :P Really hope this bug gets fixed! Thank you :)

**Comment by sainttx** [comment]
Please try using the latest development build
