### ISSUE TITLE
Animated Items/Text Not working

### ISSUE THREAD

**Issue by Biff627** [sainttx/Holograms#80]
I cant seem to get animated items or text to work on 1.13.2?
I add the example lines from spigot and it just shows the text instead of actually becoming an item or becoming animated text? The plugin as a whole works fine other than this issue? Not sure what im doing wrong

/holograms addline demo animated_item:diamond_sword 1||gold_sword 1||iron_sword 1
/holograms insertline demo 0 animated_item(500):diamond_sword 1||gold_sword 1||iron_sword 1
/holograms setline demo 0 animated_item:stone 1||dirt 1||grass 1

**Comment by Biff627** [comment]
Nevermind the commands are wrong on the site....

**Comment by AladMocu** [comment]
How did you solved it?
