### ISSUE TITLE
Holograms randomly dissapear

### ISSUE THREAD

**Issue by codgamerMC** [sainttx/Holograms#81]
So I've had for two months now this plugin installed and here and there I would casually get a hologram that dissapeared, but I recently updated the Hologram to V 2.9.1 and have restarted my server a few time here and there but the last restart removed 95% of my holograms and they refuse to be put back, what could be the issue of dissapearing Holograms?

**Comment by lbopp42** [comment]
same for me in 1.8.9 spigot version and 2.9.1 holograms

**Comment by Rewpies** [comment]
Same for me, I use Multiverse and every time I come back to the place where the Holograms are, they just dissapear...

**Comment by sainttx** [comment]
Fixed in 07f89c3cfde7ca2e6e83c903660909b1c8f7b03c
