### ISSUE TITLE
Holograms disapearing

### ISSUE THREAD

**Issue by Spooonnn** [sainttx/Holograms#84]
I have made 3 holograms at my spawn area and they seem to randomly dissapear and reapear, the only way to fix it is a server restart and with no /hologram reload it is pretty annoying, please help!

**Comment by JonMagon** [comment]
The same problem I have.

**Comment by OneCake** [comment]
I have the same issue, When the server starts, everything loads fine, but then as players spawn into chunks with holograms they unload doing /holograms refresh causes them to all load with no issues but then they will disappear again at random intervals with no console errors.

**Comment by sainttx** [comment]
Fixed in 07f89c3cfde7ca2e6e83c903660909b1c8f7b03c
