### ISSUE TITLE
Permission Nodes?

### ISSUE THREAD

**Issue by Cylizion** [sainttx/Holograms#85]
Since you have no Wiki files, I'm guessing permission nodes are set to OP only? I'd like to give non-OP players (like Admin+) to be able to create these (so they can be bought with keys or real payments). Can you create permission nodes for this plugin?

**Comment by sainttx** [comment]
Permissions are available on the plugins overview on spigot (https://www.spigotmc.org/resources/holograms.4924/)

Quote:

> All commands use the permission structure "holograms.<subcommand>" (ie. /holograms near would use the permission holograms.near).
