### ISSUE TITLE
1.15 Support?

### ISSUE THREAD

**Issue by rm2023** [sainttx/Holograms#87]
I know 1.15 just came out and I have no expectation of a version coming out this quickly, but I wanted to ask if 1.15 will be supported by this plugin

**Comment by niccholaspage** [comment]
Given the updates for previous Minecraft releases, Holograms should be updated to support 1.15. I have created a pull request to add in 1.15 support and it seems to be functioning well.

**Comment by sainttx** [comment]
Added in 4e3b789
