### ISSUE TITLE
When creating a hologram, it creates an Armor Stand item

### ISSUE THREAD

**Issue by DaniRangel** [sainttx/Holograms#88]
When creating a hologram, it creates an Armor Stand inside the hologram.

I attach images in the link
[Imgur](https://imgur.com/a/PnG3xmd)

**Comment by pedroramosdiehl** [comment]
But only shows when you are on spectator mode.

**Comment by Pankraz01** [comment]
That is normal. This is not an error! Holograms will be shown as an invisible armorstand. The only thing you see are the Nametags of the armor stand
