### ISSUE TITLE
Holograms Disappearing  and Different Lines are falling into each other

### ISSUE THREAD

**Issue by ArcticTigerr** [sainttx/Holograms#93]
Every Time I Log Onto My Server Some Holograms Lines Are Completely Gone And Some Have Fallen Into The Same Line? I Am Unable To Get Them Back By Doing The Command /holo reload. What Is Causing This Issue?

**Comment by ArcticTigerr** [comment]
I am running a spigot 1.14.4

**Comment by sainttx** [comment]
What version of holograms are you using?

**Comment by ArcticTigerr** [comment]
2.9.1

**Comment by ArcticTigerr** [comment]
is there a newer version

**Comment by ArcticTigerr** [comment]
i see there is 2.11 ill download that one

**Comment by sainttx** [comment]
Updating to 2.11 should help resolve the issues you're dealing with.

**Comment by ArcticTigerr** [comment]
Thank you!
